[build]
  publish = "out"
  command = "npm run build:netlify"
  # ビルドタイムアウトを延長
  functions = "netlify/functions"
  
# Netlify キャッシュ設定
[build.environment]
  # NetlifyでサポートされているNode.jsバージョンを明示的に指定
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"
  # Next.js build cache (Netlify対応)
  NEXT_CACHE = "true"
  NETLIFY_CACHE_ID = "next-build-cache"
  # NPM cache configuration
  NPM_CONFIG_CACHE = ".npm"
  NPM_CONFIG_PREFER_OFFLINE = "true"
  # Node.js memory settings
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Environment
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # Build debugging
  DEBUG = "next:*"
  VERBOSE = "true"
  # Netlify specific
  CI = "true"
  NETLIFY = "true"
  NETLIFY_BUILD_DEBUG = "true"
  # Firebase環境変数のデフォルト値
  NEXT_PUBLIC_FIREBASE_API_KEY = "demo-api-key"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "demo.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "demo-project"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "demo.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "123456789"
  NEXT_PUBLIC_FIREBASE_APP_ID = "demo-app-id"

# Build cache configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Netlify キャッシュとリダイレクト設定
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_NODE_ENV = "production"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[context.deploy-preview.environment]
  NEXT_PUBLIC_NODE_ENV = "development"
