[build]
  publish = ".next"
  command = "npm run clean && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  DEBUG = "*"

[[plugins]]
  package = "@netlify/plugin-nextjs"
