[build]
  publish = "out"
  command = "npm install --legacy-peer-deps; npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NODE_ENV = "production" 
  NEXT_TELEMETRY_DISABLED = "1"

# 静的エクスポート用の設定では不要
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
