[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_NODE_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_NODE_ENV = "development"
