[build]
  publish = ".next"
  command = "npm install --legacy-peer-deps --omit=optional; npx next telemetry disable; npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NODE_ENV = "production" 
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
