[build]
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NODE_ENV = "production" 
  NEXT_TELEMETRY_DISABLED = "1"

# 静的エクスポート用の設定では@netlify/plugin-nextjsは不要

# 静的エクスポート用の設定では不要
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
